"""initial schema

Revision ID: dfcd2111d184
Revises: 
Create Date: 2026-06-02 00:29:01.908171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcd2111d184'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "users" in inspector.get_table_names():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_co2_saved_kg', sa.Float(), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('line_id', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_line_id'), 'users', ['line_id'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_table('point_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_history_date_modified'), 'point_history', ['date_modified'], unique=False)
    op.create_index(op.f('ix_point_history_id'), 'point_history', ['id'], unique=False)
    op.create_index(op.f('ix_point_history_user_id'), 'point_history', ['user_id'], unique=False)
    op.create_table('shisa_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shisa_messages_conversation_id'), 'shisa_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shisa_messages_created_at'), 'shisa_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_shisa_messages_id'), 'shisa_messages', ['id'], unique=False)
    op.create_index(op.f('ix_shisa_messages_user_id'), 'shisa_messages', ['user_id'], unique=False)
    op.create_table('study_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_trip_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('begin_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('travel_time_seconds', sa.Integer(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('total_co2_emission_kg', sa.Float(), nullable=False),
    sa.Column('total_co2_saved_kg', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_trips_begin_time'), 'study_trips', ['begin_time'], unique=False)
    op.create_index(op.f('ix_study_trips_client_trip_id'), 'study_trips', ['client_trip_id'], unique=False)
    op.create_index(op.f('ix_study_trips_end_time'), 'study_trips', ['end_time'], unique=False)
    op.create_index(op.f('ix_study_trips_id'), 'study_trips', ['id'], unique=False)
    op.create_index(op.f('ix_study_trips_user_id'), 'study_trips', ['user_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('co2_saved_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_transport_mode'), 'trips', ['transport_mode'], unique=False)
    op.create_index(op.f('ix_trips_trip_time'), 'trips', ['trip_time'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('study_trip_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_trip_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('co2_emission_kg', sa.Float(), nullable=False),
    sa.Column('co2_saved_kg', sa.Float(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('travel_time_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['study_trip_id'], ['study_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_trip_legs_id'), 'study_trip_legs', ['id'], unique=False)
    op.create_index(op.f('ix_study_trip_legs_study_trip_id'), 'study_trip_legs', ['study_trip_id'], unique=False)
    op.create_index(op.f('ix_study_trip_legs_transport_mode'), 'study_trip_legs', ['transport_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_trip_legs_transport_mode'), table_name='study_trip_legs')
    op.drop_index(op.f('ix_study_trip_legs_study_trip_id'), table_name='study_trip_legs')
    op.drop_index(op.f('ix_study_trip_legs_id'), table_name='study_trip_legs')
    op.drop_table('study_trip_legs')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_trip_time'), table_name='trips')
    op.drop_index(op.f('ix_trips_transport_mode'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_study_trips_user_id'), table_name='study_trips')
    op.drop_index(op.f('ix_study_trips_id'), table_name='study_trips')
    op.drop_index(op.f('ix_study_trips_end_time'), table_name='study_trips')
    op.drop_index(op.f('ix_study_trips_client_trip_id'), table_name='study_trips')
    op.drop_index(op.f('ix_study_trips_begin_time'), table_name='study_trips')
    op.drop_table('study_trips')
    op.drop_index(op.f('ix_shisa_messages_user_id'), table_name='shisa_messages')
    op.drop_index(op.f('ix_shisa_messages_id'), table_name='shisa_messages')
    op.drop_index(op.f('ix_shisa_messages_created_at'), table_name='shisa_messages')
    op.drop_index(op.f('ix_shisa_messages_conversation_id'), table_name='shisa_messages')
    op.drop_table('shisa_messages')
    op.drop_index(op.f('ix_point_history_user_id'), table_name='point_history')
    op.drop_index(op.f('ix_point_history_id'), table_name='point_history')
    op.drop_index(op.f('ix_point_history_date_modified'), table_name='point_history')
    op.drop_table('point_history')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_line_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
